canonical: https://www.ehealth.fgov.be/standards/fhir/referral
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.be.referral
name: HL7 BE Referral Prescription WG Implementation Guide (work in progress)
title: HL7 BE Referral Prescription WG Implementation Guide (work in progress)
status: draft
version: 0.2.0
copyrightYear: 2022+
releaseLabel: STU
dependencies:
  hl7.fhir.be.core: 2.0.0
  hl7.fhir.be.medication: 1.0.0
  hl7.fhir.be.core-clinical: 1.0.0
  hl7.fhir.be.allergy: 1.0.0
